# roles/vsftpd/tasks/main.yml
---
- name: Install packages
  package:
    name: "{{ pkg }}"
    state: present
  with_items: "{{ vsftpd_packages }}"
  loop_control:
    loop_var: pkg
  ignore_errors: "{{ ansible_check_mode }}"
  register: install_packages
  until: install_packages is success
  retries: 5
  delay: 2

- name: Generate configuration files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: vsftpd
    group: vsftpd
    mode: 0644
  with_items:
    - src: "vsftpd.conf.j2"
      dest: "{{ openio_vsftpd_conf_file }}"
    - src: "pamd-vsftpd.j2"
      dest: "/etc/pam.d/{{ openio_vsftpd_pam_service_name }}"
  register: _vsftpd_conf
  tags: configure

- name: "Ensure certificate directory exists"
  file:
    path: "{{ openio_vsftpd_ssl_cert_dir }}"
    state: directory
    mode: 0750
  tags: configure

- name: "Check certificate file exists"
  stat:
    path: "{{ openio_vsftpd_ssl_cert_dir }}/{{ openio_vsftpd_ssl_cert_file }}"
  register: cert_file
  tags: configure

- name: "Fail if certificate file doesn't exist and isn't autogenerated"
  fail:
    msg: "Cannot find PEM certificate at {{ openio_vsftpd_ssl_cert_dir }}/{{ openio_vsftpd_ssl_cert_file }}"
  when:
    - not openio_vsftpd_ssl_cert_generate
    - cert_file.stat.islnk is not defined
  tags: configure

- name: "Generate a Self Signed OpenSSL certificate"
  openssl_certificate:
    path: /etc/ssl/crt/ansible.com.crt
    privatekey_path: /etc/ssl/private/ansible.com.pem
    csr_path: /etc/ssl/csr/ansible.com.csr
    provider: selfsigned
  when:
    - openio_vsftpd_ssl_cert_generate
    - cert_file.stat.islnk is not defined
  tags: configure

- name: "Restart vsftpd"
  service:
    name: vsftpd
    state: restarted
  when:
    - not openio_vsftpd_provision_only
    - _vsftpd_conf.changed
  tags: configure
...
